# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2020-01-30 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(verbose_name='date joined')),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('is_approved', models.CharField(default='NA', max_length=8)),
                ('employee', models.ForeignKey(db_column='employee', on_delete=django.db.models.deletion.CASCADE, to='cash_cog.Employee')),
            ],
            options={
                'db_table': 'expense',
            },
        ),
    ]
